spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update # jpa ddl ??
    properties:
      hibernate:
        format_sql: true # ?? ??
    defer-datasource-initialization: true # script??? hibernate ??? ?? ???? ??.
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:jboard;NON_KEYWORDS=USER
    username: sa
    password:
  sql:
    init:
      mode: embedded # ????? ?????? ??? ?? ??? ????? ??
  h2:
    console:
      enabled: true
      path: /h2-console
  thymeleaf:
    prefix: classpath:/templates/JBoard/
    cache: false # dev ???? ??? ?? ?? ??????? ??

